Name:		lv
Version:	4.51.8.00
Release:	1%{?dist}
Summary:	lv - a Powerful Multilingual File Viewer / Grep

Group:		Applications/Text
License:	GPLv2
URL:		https://github.com/shimt/lv/
Source0:	https://github.com/shimt/lv/archive/4.51.8.00.tar.gz
BuildRoot:	%(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

BuildRequires:	ncurses-devel
Requires:	ncurses

%description
- Multilingual file viewer

 lv is a powerful multilingual file viewer. Apparently, lv looks like less (1), a representative file viewer on UNIX as you know, so UNIX people (and less people on other OSs) don't have to learn a burdensome new interface. lv can be used on MSDOS ANSI terminals and almost all UNIX platforms. lv is a currently growing software, so your feedback is welcome and helpful for us to refine the future lv.

- Multiple coding systems

 lv can decode and encode multilingual streams through many coding systems, for example, ISO 2022 based coding systems such as iso-2022-jp, and EUC (Extended Unix Code) like euc-japan. Furthermore, localized coding systems such as shift-jis, big5 and HZ are also supported. lv can be used not only as a file viewer but also as a coding-system translation filter like nkf (1) and tcs (1).

- Multilingual regular expressions / Multilingual grep
    lv can recognize multi-bytes patterns as regular expressions, and lv also provides multilingual grep (1) functionality by giving it another name, lgrep. Pattern matching is conducted in the charset level, so an EUC fragment, for example, can be found in the ISO 2022 tailored streams, of course.

- Supporting the Unicode standard

 lv provides Unicode facilities which enables you to handle Unicode streams encoded in UTF-7 or UTF-8, and lv can also convert their code-points between Unicode and other charsets. So you can display Unicode or foreign texts on your terminal, using the code conversion function to your favorite charsets via Unicode. (However, MSDOS version of lv has none of the Unicode facility.)

- ANSI escape sequence through

 lv can recognize ANSI escape sequences for text decoration. So you can look ANSI-decorated streams such as colored source codes generated by another software just like intended image on ANSI terminals.

- Completely original

 lv is a completely original software including no code drawn from less and grep and other programs at all. 

%prep
%setup -q -n lv-4.51.8.00


%build
cd src
chmod 775 configure
./configure --prefix='%{_prefix}' --libdir='%{_datadir}'
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT
cd src
mkdir -p \
	$RPM_BUILD_ROOT \
	$RPM_BUILD_ROOT%{_bindir} \
	$RPM_BUILD_ROOT%{_datadir}/lv \
	$RPM_BUILD_ROOT%{_datadir}/man
make install \
	prefix=$RPM_BUILD_ROOT%{_prefix} \
	exec_prefix=$RPM_BUILD_ROOT%{_exec_prefix} \
	bindir=$RPM_BUILD_ROOT%{_bindir} \
	libdir=$RPM_BUILD_ROOT%{_datadir} \
	mandir=$RPM_BUILD_ROOT%{_datadir}/man
chmod 755 $RPM_BUILD_ROOT%{_bindir}/*


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc
%{_bindir}/lgrep
%{_bindir}/lv
%{_datadir}/lv/lv.hlp

%changelog

